config/routes.rb
Rails.application.routes.draw do
  resources :detalhes_vendas
  resources :vendas
  resources :produtos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/detalhes_venda.rb
class DetalhesVenda < ApplicationRecord
  belongs_to :venda
  belongs_to :produto
end

app/controllers/detalhes_vendas_controller.rb
class DetalhesVendasController < ApplicationController
  before_action :set_detalhes_venda, only: %i[ show edit update destroy ]

  # GET /detalhes_vendas or /detalhes_vendas.json
  def index
    @detalhes_vendas = DetalhesVenda.all
  end

  # GET /detalhes_vendas/1 or /detalhes_vendas/1.json
  def show
  end

  # GET /detalhes_vendas/new
  def new
    @detalhes_venda = DetalhesVenda.new
  end

  # GET /detalhes_vendas/1/edit
  def edit
  end

  # POST /detalhes_vendas or /detalhes_vendas.json
  def create
    @detalhes_venda = DetalhesVenda.new(detalhes_venda_params)

    respond_to do |format|
      if @detalhes_venda.save
        format.html { redirect_to @detalhes_venda, notice: "Detalhes venda was successfully created." }
        format.json { render :show, status: :created, location: @detalhes_venda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalhes_venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalhes_vendas/1 or /detalhes_vendas/1.json
  def update
    respond_to do |format|
      if @detalhes_venda.update(detalhes_venda_params)
        format.html { redirect_to @detalhes_venda, notice: "Detalhes venda was successfully updated." }
        format.json { render :show, status: :ok, location: @detalhes_venda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detalhes_venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalhes_vendas/1 or /detalhes_vendas/1.json
  def destroy
    @detalhes_venda.destroy!

    respond_to do |format|
      format.html { redirect_to detalhes_vendas_path, status: :see_other, notice: "Detalhes venda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalhes_venda
      @detalhes_venda = DetalhesVenda.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def detalhes_venda_params
      params.expect(detalhes_venda: [ :venda_id, :produto_id, :quantidade, :subtotal ])
    end
end

app/helpers/detalhes_vendas_helper.rb
module DetalhesVendasHelper
end

app/views/detalhes_vendas/_detalhes_venda.html.erb
<div id="<%= dom_id detalhes_venda %>">
  <p>
    <strong>Venda:</strong>
    <%= detalhes_venda.venda_id %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= detalhes_venda.produto_id %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= detalhes_venda.quantidade %>
  </p>

  <p>
    <strong>Subtotal:</strong>
    <%= detalhes_venda.subtotal %>
  </p>

</div>

app/views/detalhes_vendas/_form.html.erb
<%= form_with(model: detalhes_venda) do |form| %>
  <% if detalhes_venda.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detalhes_venda.errors.count, "error") %> prohibited this detalhes_venda from being saved:</h2>

      <ul>
        <% detalhes_venda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :venda_id, style: "display: block" %>
    <%= form.text_field :venda_id %>
  </div>

  <div>
    <%= form.label :produto_id, style: "display: block" %>
    <%= form.text_field :produto_id %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :subtotal, style: "display: block" %>
    <%= form.text_field :subtotal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/detalhes_vendas/edit.html.erb
<% content_for :title, "Editing detalhes venda" %>

<h1>Editing detalhes venda</h1>

<%= render "form", detalhes_venda: @detalhes_venda %>

<br>

<div>
  <%= link_to "Show this detalhes venda", @detalhes_venda %> |
  <%= link_to "Back to detalhes vendas", detalhes_vendas_path %>
</div>

app/views/detalhes_vendas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Detalhes vendas" %>

<h1>Detalhes vendas</h1>

<div id="detalhes_vendas">
  <% @detalhes_vendas.each do |detalhes_venda| %>
    <%= render detalhes_venda %>
    <p>
      <%= link_to "Show this detalhes venda", detalhes_venda %>
    </p>
  <% end %>
</div>

<%= link_to "New detalhes venda", new_detalhes_venda_path %>

app/views/detalhes_vendas/new.html.erb
<% content_for :title, "New detalhes venda" %>

<h1>New detalhes venda</h1>

<%= render "form", detalhes_venda: @detalhes_venda %>

<br>

<div>
  <%= link_to "Back to detalhes vendas", detalhes_vendas_path %>
</div>

app/views/detalhes_vendas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detalhes_venda %>

<div>
  <%= link_to "Edit this detalhes venda", edit_detalhes_venda_path(@detalhes_venda) %> |
  <%= link_to "Back to detalhes vendas", detalhes_vendas_path %>

  <%= button_to "Destroy this detalhes venda", @detalhes_venda, method: :delete %>
</div>