config/routes.rb
Rails.application.routes.draw do
  resources :detalhes_vendas
  resources :vendas
  resources :produtos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/produto.rb
class Produto < ApplicationRecord
    has_many :detalhes_vendas

end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_path, status: :see_other, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.expect(produto: [ :nome, :preco, :estoque ])
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :preco, style: "display: block" %>
    <%= form.text_field :preco %>
  </div>

  <div>
    <%= form.label :estoque, style: "display: block" %>
    <%= form.number_field :estoque %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">
  <p>
    <strong>Nome:</strong>
    <%= produto.nome %>
  </p>

  <p>
    <strong>Preco:</strong>
    <%= produto.preco %>
  </p>

  <p>
    <strong>Estoque:</strong>
    <%= produto.estoque %>
  </p>

</div>

app/views/produtos/edit.html.erb
<% content_for :title, "Editing produto" %>

<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Show this produto", @produto %> |
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Produtos" %>

<h1>Produtos</h1>

<div id="produtos">
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Show this produto", produto %>
    </p>
  <% end %>
</div>

<%= link_to "New produto", new_produto_path %>

app/views/produtos/new.html.erb
<% content_for :title, "New produto" %>

<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Edit this produto", edit_produto_path(@produto) %> |
  <%= link_to "Back to produtos", produtos_path %>

  <%= button_to "Destroy this produto", @produto, method: :delete %>
</div>