config/routes.rb
Rails.application.routes.draw do
  resources :detalhes_vendas
  resources :vendas
  resources :produtos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :cliente
  has_many :detalhes_vendas, dependent: :destroy
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: %i[ show edit update destroy ]

  # GET /vendas or /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1 or /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas or /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to @venda, notice: "Venda was successfully created." }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1 or /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: "Venda was successfully updated." }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1 or /vendas/1.json
  def destroy
    @venda.destroy!

    respond_to do |format|
      format.html { redirect_to vendas_path, status: :see_other, notice: "Venda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def venda_params
      params.expect(venda: [ :cliente_id, :total ])
    end
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/vendas/_form.html.erb
<%= form_with(model: venda) do |form| %>
  <% if venda.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
        <% venda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
    
  </div>
  <div class="field">
  <%= form.label :cliente_id %>
  <%= form.collection_select :cliente_id, Cliente.all, :id, :nome %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vendas/_venda.html.erb
<div id="<%= dom_id venda %>">
  <p>
    <strong>Cliente:</strong>
    <%= venda.cliente_id %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= venda.total %>
  </p>

</div>

app/views/vendas/edit.html.erb
<% content_for :title, "Editing venda" %>

<h1>Editing venda</h1>

<%= render "form", venda: @venda %>

<br>

<div>
  <%= link_to "Show this venda", @venda %> |
  <%= link_to "Back to vendas", vendas_path %>
</div>

app/views/vendas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Vendas" %>

<h1>Vendas</h1>

<div id="vendas">
  <% @vendas.each do |venda| %>
    <%= render venda %>
    <p>
      <%= link_to "Show this venda", venda %>
    </p>
  <% end %>
</div>

<%= link_to "New venda", new_venda_path %>

app/views/vendas/new.html.erb
<% content_for :title, "New venda" %>

<h1>New venda</h1>

<%= render "form", venda: @venda %>

<br>

<div>
  <%= link_to "Back to vendas", vendas_path %>
</div>

app/views/vendas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @venda %>

<div>
  <%= link_to "Edit this venda", edit_venda_path(@venda) %> |
  <%= link_to "Back to vendas", vendas_path %>

  <%= button_to "Destroy this venda", @venda, method: :delete %>
</div>